server.port=8080
spring.application.name=gateway

spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=http://auth-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**

spring.cloud.gateway.routes[1].id=employee-service
spring.cloud.gateway.routes[1].uri=http://employee-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/employees/**

spring.cloud.gateway.routes[2].id=attendance-service
spring.cloud.gateway.routes[2].uri=http://attendance-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/attendance/**

spring.cloud.gateway.routes[3].id=leave-service
spring.cloud.gateway.routes[3].uri=http://leave-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/leaves/**

spring.cloud.gateway.routes[4].id=payroll-service
spring.cloud.gateway.routes[4].uri=http://payroll-service:8085
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/payroll/**
